version: '3.9'
name: 'cinema-ugc'

services:
  event-collector:
    build: ./event_collector
    container_name: event-collector
    env_file:
      - .env
    ports:
      - '8000:8000'
    restart: unless-stopped
    depends_on:
      - rabbitmq

  event-processor:
    build: ./event_processor
    container_name: event-processor
    env_file:
      - .env
    restart: unless-stopped
    depends_on:
      - rabbitmq
      - clickhouse-node1
      - clickhouse-node2
      - clickhouse-node3
      - clickhouse-node4

  rabbitmq:
    image: 'rabbitmq:3.11.18'
    container_name: rabbitmq
    ports:
      - '5672:5672'
      - '15672:15672'
    restart: unless-stopped
    environment:
      - RABBITMQ_DEFAULT_USER
      - RABBITMQ_DEFAULT_PASS
      - RABBITMQ_DEFAULT_VHOST

  zookeeper:
    image: zookeeper:3.8
    container_name: zookeeper
    hostname: zookeeper

  clickhouse-node1:
    image: clickhouse/clickhouse-server:23
    container_name: clickhouse-node1
    hostname: clickhouse-node1
    ports:
      - "8123:8123"
      - "9000:9000"
    volumes:
      - ./clickhouse/prod/node1:/etc/clickhouse-server
    depends_on:
      - zookeeper

  clickhouse-node2:
    image: clickhouse/clickhouse-server:23
    container_name: clickhouse-node2
    hostname: clickhouse-node2
    ports:
      - "8124:8123"
      - "9001:9000"
    volumes:
      - ./clickhouse/prod/node2:/etc/clickhouse-server
    depends_on:
      - zookeeper

  clickhouse-node3:
    image: clickhouse/clickhouse-server:23
    container_name: clickhouse-node3
    hostname: clickhouse-node3
    ports:
      - "8125:8123"
      - "9002:9000"
    volumes:
      - ./clickhouse/prod/node3:/etc/clickhouse-server
    depends_on:
      - zookeeper

  clickhouse-node4:
    image: clickhouse/clickhouse-server:23
    container_name: clickhouse-node4
    hostname: clickhouse-node4
    ports:
      - "8126:8123"
      - "9003:9000"
    volumes:
      - ./clickhouse/prod/node4:/etc/clickhouse-server
    depends_on:
      - zookeeper

  mongo:
    image: 'mongo:6.0.13'
    container_name: mongo
    ports:
      - '27017:27017'
    restart: unless-stopped
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
    volumes:
      - mongo_data:/data/db

  logstash:
    image: logstash:8.6.2
    container_name: logstash
    ports:
      - '5044:5044/udp'
      - '5044:5044/tcp'
      - '514:514/udp'
    restart: unless-stopped
    environment:
      XPACK_MONITORING_ENABLED: "false"
      ES_HOST: "elasticsearch:9200"
    volumes:
      - ./elk/logstash.conf:/config/logstash.conf:ro
    command: logstash -f /config/logstash.conf

  elasticsearch:
    image: elasticsearch:8.6.2
    container_name: elasticsearch
    ports:
      - '9200:9200'
    restart: unless-stopped
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    volumes:
      - log_data:/usr/share/elasticsearch/data
    # need to avoid memory issues on startup
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 4G
        reservations:
          cpus: '0.5'
          memory: 2G

  kibana:
    image: kibana:8.6.2
    container_name: kibana
    ports:
      - '5601:5601'
    restart: unless-stopped
    depends_on:
      - elasticsearch
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200

volumes:
  log_data:
  mongo_data: