version: '3.9'
name: 'cinema-ugc-dev'

services:
  kafka-ui:
    image: provectuslabs/kafka-ui:v0.7.0
    container_name: kafka-ui
    ports:
      - '8080:8080'
    restart: unless-stopped
    depends_on:
      - kafka
    environment:
      - KAFKA_CLUSTERS_0_BOOTSTRAP_SERVERS=kafka:9092
      - KAFKA_CLUSTERS_0_NAME=kafka

  kafka:
    image: 'bitnami/kafka:latest'
    container_name: kafka-dev
    ports:
      - '9094:9094'
    restart: unless-stopped
    environment:
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,EXTERNAL://localhost:9094
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER

  rabbitmq:
    image: 'rabbitmq:3.11.18'
    container_name: rabbitmq-dev
    ports:
      - '5672:5672'
      - '15672:15672'
    restart: unless-stopped
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
      - RABBITMQ_DEFAULT_VHOST=/

  clickhouse:
    image: clickhouse/clickhouse-server:23
    container_name: clickhouse-dev
    ports:
      - "8123:8123"
      - "9000:9000"
    volumes:
      - ./clickhouse/dev/master:/etc/clickhouse-server

  redis:
    image: 'redis:6.2.5'
    container_name: redis-dev
    ports:
      - '6379:6379'
    restart: unless-stopped

  mongo:
    image: 'mongo:6.0.13'
    container_name: mongo-dev
    ports:
      - '27017:27017'
    restart: unless-stopped
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
    volumes:
      - ./mongo/dev/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro