@startuml
skinparam componentStyle uml2
actor Client
actor Admin
actor Analytic
component Frontend
component AdminService
component ContentService
component AuthService
component UGCService
control ETL
database Postgres #blue
database Elastic #lightgreen
database Redis #red
database Clickhouse #orange
queue Kafka

Client -> Frontend: Films consuming
Frontend <-down-> AuthService: Authentication
Frontend -> ContentService: Search films, actors etc...
Admin -> AdminService: Films CRUD
AdminService <-> AuthService: Athentication
AuthService -down-> Postgres
AdminService -> Postgres
ContentService <-> Redis: cached responses
ContentService <-down-> Elastic: movies, actors, genres...
Postgres -> ETL: Data
ETL -> Elastic: updating...
Frontend -up-> UGCService: User events (Lots of data)
UGCService -> Kafka: event batch
Kafka -> Clickhouse
Analytic -left-> Clickhouse: do analytic stuff
@enduml
