name: Python application

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      matrix:
        python-version: [3.9, 3.10, 3.11]

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Create directories
      run: |
        mkdir -p reports/wemake-python-styleguide/
        mkdir -p reports/mypy/
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install wemake-python-styleguide pytest mypy flake8-html lxml
        if [ -f event_processor/requirements.txt ]; then pip install -r event_processor/requirements.txt; fi
        if [ -f event_collector/requirements.txt ]; then pip install -r event_collector/requirements.txt; fi
        if [ -f event_collector/requirements-test.txt ]; then pip install -r event_collector/requirements-test.txt; fi

    - name: Lint with wemake-python-styleguide
      run: |
        flake8 . --exit-zero --format=html --htmldir=reports/wemake-python-styleguide/

    - name: Mypy checking
      run: |
        mypy --html-report reports/mypy/

    - name: Test with pytest
      run: |
        python -m pytest

    - name: Upload reports
      uses: actions/upload-artifact@v2
      with:
        name: reports
        path: reports/
        
  notify:
    needs: build
    if: always()
    runs-on: ubuntu-latest
    steps:
      - name: send notification in telegram
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            New build in Pull Request:  ${{ github.head_ref }} ---> ${{ github.base_ref }}.
            Pipeline status: ${{ needs.build.result }}.
            Pull Request title: ${{ github.event.pull_request.title }}
